### ISSUE TITLE
How to understand Client implement Cmdable interface in source code?

### ISSUE THREAD

**Issue by tomjamescn** [go-redis/redis#1089]
hi, i'm new to golang, i use go-redis/redis in our project, but i can not understand how `Client` (redis.go:462) implement `Cmdable`(commands.go:51) interface.

`Client` struct embedding `*client` which embedding `cmdable` type. `cmdable` type (commands.go:310) is a type definition `type cmdable func(cmd Cmder) error` and implement some method of `Cmdable` interface. 

In `init` method of `*Client`,  `c.cmdable = c.Process`,  is this the key? 

`Process` method of `*Client` have no method like `cmdaboe` interface. Am i missing something?

could anyone explain? thank you very much.

**Comment by vmihailenco** [comment]
You probably confuse struct `cmdable` and interface `Cmdable`. struct `cmdable` implements `Cmdable` interface and is embeded in `Client` - nothing complicated besides confusing naming.

`c.cmdable = c.Process` works because it is defined as `type cmdable func(cmd Cmder) error`. Alternatively it can be defined as

```
type cmdable struct {
    fn func(cmd Cmder) error
}
```

and used as `c.cmdable.fn = c.Process` which would be less confusing but still the same.

**Comment by tomjamescn** [comment]
@vmihailenco  I got it. Thank you very much.
