### ISSUE TITLE
[Need Confirm]Connection spike issue from client 

### ISSUE THREAD

**Issue by yifa-n** [go-redis/redis#1226]
We use Go-redis lib in my services 
Found sometimes connections from Redis latency increased immediately with connections spike

Tried dig into connection part

we found that 
`
func (p *ConnPool) newConn(ctx context.Context, pooled bool) (*Conn, error) {}
`
In this func , when client try get a connection but without available one in pool , client will create a connection(temporary) anyway and remove it after use

But every connection create event require mutex lock , it seems not so efficient and maybe have load issue on high concurrency scenario

I think for `conns` in pool , could conns only control connections which count in pool size 
For temporary connection work, could it's live cycle be `create->use->detele` without in `conns`

Need your confirm, give us some advices, thanks

**Comment by vmihailenco** [comment]
>client will create a connection(temporary) anyway and remove it after use

Could you point me to the code?

AFAIK we do something like that only when you have `MinIdleConns` and there is a race between `checkMinIdleConns` and `pool.Get`. It should not happen often and the effect should not be measurable. You can always disable `MinIdleConns` (it is disabled by default) and check if the problem is fixed.

>But every connection create event require mutex lock

We only hold mutex to `append` or remove element from the slice - it is super fast and does not happen often. mutex is *not* hold when we dial new connection.

>For temporary connection work, could it's live cycle be create->use->detele without in conns

The problem here is that connection can be blocked in waiting/reading the data (e.g. from Redis channel) and so we must save pointer to the connection in the list somewhere so we can close the connection when client is closed. This way your program can exit cleanly without waiting 10-30 seconds for the connection to be returned to the pool and closed properly.

**Comment by yifa-n** [comment]
First thank you for reply 

>  It should not happen often
True

From code we read , main processes below
`
func (p *ConnPool) Get() (*Conn, error) {
	for {
		p.connsMu.Lock()
		cn := p.popIdle()
		p.connsMu.Unlock()
		if cn == nil {
			break
		}
		return cn, nil
	}
	newcn, err := p._NewConn(true)
}
`

In `_NewConn`

`
func (p *ConnPool) _NewConn(pooled bool) (*Conn, error) {
	cn, err := p.newConn(pooled)
	p.connsMu.Lock()
	p.conns = append(p.conns, cn)
	if pooled {
		if p.poolSize < p.opt.PoolSize {
			p.poolSize++
		} else {
			cn.pooled = false
		}
	}
	p.connsMu.Unlock()
	return cn, nil
}
`
i think it create then decide count into poolSize or not

**Comment by yifa-n** [comment]
em , i did not set MinIdleConns .
But my point was once get a connection from pool , even if connections more than pool size it also create a connection .... 
please correct me if wrong

**Comment by vmihailenco** [comment]
There are functions `getTurn`, `waitTurn`, and `freeTurn` that make sure that we call `_NewConn` only when pool is not full and there are no idle connections. Does that help?

**Comment by yifa-n** [comment]
Got you are right, i will check it further ,thanks!

**Comment by stan-sack** [comment]
@yifa-n did you ever deal with this. I was seeing the same thing - I run out of idle connections, then shortly after, my servers open like 300k connections and DOS my redis. 

I wasn't using `MinIdleConns` - I just set `PoolSize = 40 * num threads`. Hoping that `MinIdleConns` solves the problem.

**Comment by yifa-n** [comment]
To be honest, there is no such QPS increased since i set a more strictly hystrix setting
I suspect in a huge load case , it is not go-redis but a golang issue

**Comment by stan-sack** [comment]
thankyou. that is very helpful!
