### ISSUE TITLE
Is There Any Way To Connect With a URL?

### ISSUE THREAD

**Issue by gmoore** [go-redis/redis#129]
Our Go app runs on Heroku and we were going to use the REDISTOGO Heroku add-on. REDISTOGO publishes REDISTOGO_URL environment variable that our app is supposed to consume. It's in this format:

`redis://username:password@server.redistogo.com:port/`

Flipping though the API docs for go-redis, it doesn't look like Conn Options supports a URL connect string or even a username. Is this the case? I'm new to Go and I just want to make sure I'm reading it right.

If this is the case, I may try to send a PR that'll take a URL connect string a chop it up and use that.

**Comment by vmihailenco** [comment]
There was a similar issue several days ago - https://github.com/go-redis/redis/issues/128

> Is this the case?

Yes, you are supposed to connect using `redis.NewClient` and `redis.Options` - http://godoc.org/gopkg.in/redis.v3#example-NewClient

>If this is the case, I may try to send a PR that'll take a URL connect string a chop it up and use that.

I would prefer to not include alternative configuration format in additional to `redis.Options`, because
- It is additional API and complexity.
- We have several flavors of options, e.g. `redis.Options`, `redis.ClusterOptions`, `redis.RingOptions` and `redis.FailoverOptions`. It is not clear how to elegantly support all of them.

But I would accept an example similar to https://github.com/go-redis/redis/blob/master/example_test.go#L22, which shows how to parse an URL and build `redis.Options`. Then we can consider adding it to the readme. Probably @cousine can share his approach with us :)

**Comment by gmoore** [comment]
It turns out that the username in REDISTOGO_URL isn't needed. After we figured that out it wasn't much to parse the whole string into "host:port" and "password" values. That worked just fine. Thanks!

**Comment by cousine** [comment]
I just saw this now so I'll place the solution I took for future reference:

	import(
	  "net/url"
	  "gopkg.in/redis.v3"
	)

	redisUrl, _ := url.Parse("redis://username:password@host:port")
	redisPassword, _ := redisUrl.User.Password()
	redisDB, _ := 0
	redisOptions := redis.Options{
		Addr:     redisUrl.Host,
		Password: redisPassword,
		DB:       redisDB,
	}

	redisClient := redis.NewClient(&redisOptions)

**Comment by astriddg** [comment]
So I've followed your solution and now get `NOAUTH Authentication required`. Sounds like the connection was refused? Any idea how you check this?

**Comment by vmihailenco** [comment]
The new/better way is shown [here](https://godoc.org/github.com/go-redis/redis#example-ParseURL)
