### ISSUE TITLE
go-redis v7 7.2.0 with redis 5.0.8 seems to hit a dead lock

### ISSUE THREAD

**Issue by shrivardhan92** [go-redis/redis#1317]
We do not see this problem with 5.0.4 redis

Sample code:
```
// create cluster client
rdb := 	redis.NewClusterClient(clusterOptions)

// spawn of 10 concurrent writers
for i := 0; i < 10; i++ {
  go func() {
    defer wg.Done()
    ci.processEvents(rdb)
  }()
}

```

**in 5.0.8 we see a dead lock. We see exactly 10 go-routines waiting on github.com/go-redis/redis/v7/internal.(*Once).Do***

[go-redis-issue.log](https://github.com/go-redis/redis/files/4576984/go-redis-issue.log)

Links to:  https://github.com/go-redis/redis/issues/1313

**Comment by fishy** [comment]
I don't think this is really a deadlock, nor do I think this is related to #1313. I think this is just that in the current implementation `internal.Once` could hold the lock for excessively long period time when there are problems talking to the cluster, making it look like a deadlock.

The rest is copied from the discussion on #1404 (cc @rbg @vmihailenco ):

We recently started to use go-redis to do some high volume requests, and observed occasional error/latency spikes. We tried redispipe and never observe any error/latency spike with the same usage. We do prefer go-redis overall feature wise (redispipe works better for this use case, but for it's lacking on some other, nor generic use cases), and want to avoid the situation of using two different redis libraries for different use cases in the same code base.

The retries on the errors here, is an example of go-redis code making a bad situation worse, as the reason I described above. I can understand the rational of "we only want to cache successes, not errors". But the current implementation could result in a lock being held for excessively long period of time. I don't know what's a good fix right now. Maybe we can make the timeout in `ClusterClient.cmdsInfo` more configurable? That's just a random idea.

Also we tried to apply this patch, and still observed the error/latency spikes (but probably less frequent), so this is not the only problem we hit.

**Comment by vmihailenco** [comment]
I wonder if you use `ReadTimeout` and `WriteTimeout` options? They allow to configure how much time cmdsInfo spends waiting for a response from Redis. There should not be a deadlock, but ClusterClient won't process commands until commands info is available. That seems okay because ClusterClient can't properly route commands without that info.

**Comment by fishy** [comment]
> I wonder if you use `ReadTimeout` and `WriteTimeout` options? They allow to configure how much time cmdsInfo spends waiting for a response from Redis. There should not be a deadlock, but ClusterClient won't process commands until commands info is available. That seems okay because ClusterClient can't properly route commands without that info.

We used to set read/write/connect timeouts, but we stopped doing that and switched to rely solely on context timeout.

For most of the operations, this is the function to actually decide which timeout to use: https://github.com/go-redis/redis/blob/f2645d373d0ec8b2bcb48417be8c835ce353b7b3/internal/pool/conn.go#L106

Basically that function pick the earlier one between read/write/connect timeout and the context timeout as the timeout to use. This is the perfect solution, as in reality, context timeout is set for the whole request (function call to the go-redis library), while read/write/connect is set for a single read/write/connect operation. For example, we give every request to take up to 500ms, we would set the context timeout to be 500ms to reflect that. If the read/write timeout is something lower than that (say 200ms), that poses a risk that we would abandon the request prematurely (for example, that read/write request actually takes 250ms to finish, which is still acceptable under the 500ms per request timeout, but would be overridden by the 200ms read/write timeout and cause timeout error). As a result, if we would need to set a global, read/write/connect timeout, that need to be longer than the longest pre-request timeout the whole code allows.

We could set a long read/write/connect timeout for that case to use, which would improve the situation, but since that's trying the requests in a for loop, for every failed requests, it would still cause the lock to be held for a long period of time (but would be shorter than no timeout set).

**Comment by vmihailenco** [comment]
>it would still cause the lock to be held for a long period of time

Without commands information we can't properly route commands - go-redis will send commands to random nodes. It is not the end of the world, but introduces another failure mode...

What do you think about trying 3 random nodes in https://github.com/go-redis/redis/blob/master/cluster.go#L1544-L1569 ? This will limit the time we wait for commands to load.

>We used to set read/write/connect timeouts, but we stopped doing that and switched to rely solely on context timeout.

This explains the "deadlock" though you must be rather unlucky to reliable trigger it :)

You still have to set ReadTimeout and WriteTimeout to some relatively high value. go-redis will pick the lowest value between context and ReadTimeout. It is useful for case like this when context.Context does not have deadline.

**Comment by fishy** [comment]
>What do you think about trying 3 random nodes in https://github.com/go-redis/redis/blob/master/cluster.go#L1544-L1569 ? This will limit the time we wait for commands to load.

Yea I think that would help.

To clarify we didn't really get "deadlock" (I'm not the OP reporting this issue). We got occasional error and latency spikes. I don't believe we actually hit this particular one, the one we hit are more likely the lock in the client pool. I was just going through the locks used in this library and noticed that this one could be held for long period of time. The lock in client pool might need some more work to fix, e.g. use channels instead of slice+lock to implement the pool.

But I agree that we still need a high value of read/write timeout, otherwise if we hit this one it will be very long.

**Comment by vmihailenco** [comment]
@shrivardhan92 you should try v7.4.0 and make sure to set Read/Write timeouts properly.
