### ISSUE TITLE
Add ExpectArrayLen / ReadFixedArray

### ISSUE THREAD

**Issue by vmihailenco** [go-redis/redis#1508]
```go
func (r *Reader) ReadFixedArray(caller string, n int) error {
	got, err := r.ReadArrayLen()
	if err != nil {
		return err
	}
	if n != got {
		return fmt.Errorf("redis: %s: unexpected array length; want %d, got %d", caller, n, got)
	}
	return nil
}
```

**Comment by icholy** [comment]
I was thinking about the lack of context information in the error too. My reasoning for leaving it out is that it's not something that should ever happen. When you hit this error, it indicates a bug in the library (not user code). An incorrect number of array elements is no different than trying to read an int reply instead of a string reply. Yet those methods also don't have a "caller" parameter. If we went to add context to the error, we should do it consistently further up the call chain.

**Comment by vmihailenco** [comment]
It is a big in the library and users will report it here. Without context I have no idea where it happens...

**Comment by vmihailenco** [comment]
Fixed by https://github.com/go-redis/redis/pull/1739
