### ISSUE TITLE
Consider removing redis.Nil error from Pipeline.Exec function generated by subcommands？

### ISSUE THREAD

**Issue by LaodaLuo** [go-redis/redis#1860]
For example, it has two strings 'a' and 'b' in redis, when I try to get 'a', 'b' and 'c' in pipeline it ocur an redis.Nil error from pipeline.exec function.

Next, I use for range to process every cmder's result and got error only in get 'c' command.

**Comment by LaodaLuo** [comment]
what I mean is that error return by Pileline.Exec seems like an error just for pipeline it self, but the error actually generated by subcommands.

So when I wanna use pipeline I should write something like 'if err != nil && err != redis.Nil { return }'

**Comment by vmihailenco** [comment]
I am not sure the suggested behavior is better - sometimes you want it this way and sometimes the other way. For example, if your pipeline consists of GET commands, it can be handy to just check for `pipe.Err()` to be sure that all keys were loaded successfully.

Closing since it is too late to make such change without a very good reason.
