### ISSUE TITLE
ZMScore should return SliceCmd not FloatSliceCmd

### ISSUE THREAD

**Issue by magicdvd** [go-redis/redis#1875]
ZMScore should return SliceCmd as result which is similar to HMGet

Default Value for FloatSlice "0" for nil item will be confused with the item which has score "0" in zset.

**Comment by monkey92t** [comment]
If it is changed to SliceCmd, it is very unfriendly to users. I think that for most cases, score=0 will not cause a problem. If you really need to distinguish between 0 and nil, it seems you can try redis.Do(cmd).

**Comment by wangfengfly** [comment]
This should not cause problems, in my opinion. if one has nil value for score, we can also think that it has "0" score in zset, and it will cause some problems, you may process this special case in your service logic?

**Comment by monkey92t** [comment]
If you have a different opinion, you can reopen the question

**Comment by magicdvd** [comment]
if you have a list for user score in zset
UID.   score
1.        3
2.       2
3.       1
4.       0
5.       -1 
6.      -2 

ZMScore for query user(1,2,3,4,5,6,7).      7 and 4 has same value 0.   I can not know  7 is not in the list.

The same usage for HMGet has no confusion.

You can say i am able use score begin with 1 to avoid this problem. That is application logical, you  can not force developer to change logical to follow dep's limitaion( The limitiaon make the original data modified)

This is my concern.

**Comment by monkey92t** [comment]
Yes, I understand what you mean;

What I want to say is that in most cases the default value of 0 will not cause problems, just like the default value of an int type variable is 0;

If you have to distinguish between 0 and nil, you can try this:

```go
db.ZAdd(ctx, "key", &redis.Z{Score: 1, Member: "one"}, &redis.Z{Score: 0, Member: "two"})
res, _ := db.Do(ctx, "zmscore", "key", "one", "two", "three").Slice()
fmt.Println(res)
// [1 0 <nil>]
```

**Comment by jvnuw** [comment]
Redis has documented behaviour for ZMScore: "For every member that does not exist in the sorted set, a nil value is returned." [[1]](https://redis.io/docs/latest/commands/zmscore/)

The types used with ZMScore in go-redis forces it to be inconsistent with the Redis docs. This difference is not documented on the go-redis ZMScore function [[2](https://pkg.go.dev/github.com/redis/go-redis/v9#Client.ZMScore)] nor the go-redis documentation about `redis.Nil` [[3](https://redis.uptrace.dev/guide/go-redis.html#redis-nil)]

I believe ZMScore could have been typed in a few different ways which would have avoided the OP's issue:

1. A `FloatPtrSliceCmd`. This would accurately follow the Redis documentation, while retaining better typing than `SliceCmd`, at the expense of approximately double the memory on most machines. A `[]*float64` is still less convenient than a `[]float64` in some cases, but the `FloatPtrSliceCmd` could make the non-nil `[]*float64` elements point to elements in an equal size `[]float64` and reveal both.
2. Additional `[]bool` slice on a `FloatOkSliceCmd`. This deviates a bit from Redis, but more closely follows the Go convention of an extra bool to indicate existence (similar to `(float64, bool)` rather than `*float64`).
3. Using `NaN` to represent `nil` in a `FloatSliceCmd`. IIUC `0` is a valid score in a ZSet, whereas `NaN` is not. This would be more surprising than solutions 1 or 2, but address the OP's issue with the existing go-redis ZMScore types.

**Comment by stephenmax-zhang** [comment]
Since go-redis ZMScore treat nil as zero, how should I check a bunch of member existence in a zset?
pipeline/txpipeline + bunch of ZScore/ZRANK/ZREVRANK?
it‘s not elegant, I vote for opinion of @jvnuw
