### ISSUE TITLE
Add option to disable reaper logging

### ISSUE THREAD

**Issue by R4CHI7** [go-redis/redis#323]
I am using this package on a production system. After configuring the pool size options, the log statement:
`redis: 2016/05/20 11:59:20 reaper: removed 1 stale conns (TotalConns=0 FreeConns=1 Requests=790 Hits=783 Timeouts=0)`
keeps appearing every minute. It is filling up my logs pretty fast and consuming a lot of disk space.
I checked the code and there is an `if` condition in the method `Debugf` in `internal/log.go`:
```go
if !Debug {
    return
}
```

I think the same should be present in the `Logf` method. Also, I think there should be methods to set the `Debug` flag.

**Comment by vmihailenco** [comment]
I can add `Logger *log.Logger` and `DebugLogger*log.Logger` for normal and debug log levels. But that does not look very nice/scalable and I can't say which logs are important and which are not. Clearly all of them are not very important, because otherwise they should be converted into errors or at least should not be discarded by default. For now I prefer to do nothing :)

**Comment by R4CHI7** [comment]
Fair enough. I'm just worried about my log files :stuck_out_tongue:

**Comment by vmihailenco** [comment]
Closing - logs are disabled by default.
