### ISSUE TITLE
Scalability of Channels (Pub/Sub)

### ISSUE THREAD

**Issue by pjebs** [go-redis/redis#334]
I'm building a real-time text based chat program where people can chat with ONLY 1 other person.
Each person can chat with 1 other person, but the aim is they can chat with Many people at once. (i.e. MANY one to one chats with different people). The aim is to have it scaleable, not necessarily to snapchat's level, but enough for 1 City.

I'm just wondering what is more scaleable:

* Having 1 channel for the **entire** application and filtering who the **message is for** and **who sent the message** based on the data encoded in the message

OR

* Having 1 channel for **each** person and all the different people sending messages to that person send their messages through that channel with data encoding **who sent the message**

OR

* Have an individual channel for EACH Chat between 2 people.

OR

* For Option 1 (1 channel for entire app), perhaps an intermediate solution of having 1 channel per city.

I'm wondering what approach is best for Go and Redis. If there is no clear cut answer, what the conditions/criteria are for making the decision.

**Comment by pjebs** [comment]
If option 2, the viability of having 1 subscriber connection listening to all relevant channels rather than a different connection per channel

**Comment by vmihailenco** [comment]
This is general Go/Redis question so you probably get better answers on golang-nuts/stackoverflow etc.

1 channel for each person sounds bad, because it looks like you will have to listen on thousands/millions of channels and I don't imagine how this can work better than 1 channel per Redis Server (even if you use `PSUBSCRIBE *` to subscribe for all channels). So I would create 1 channel for each Redis Server you have and use some hashing function to distribute load between Redis Servers. Probably Redis Cluster client should/can help you with this.
