### ISSUE TITLE
Would you consider allowing NewFailoverClient for *ring.Ring?

### ISSUE THREAD

**Issue by didip** [go-redis/redis#382]
I think there could be a good HA story here.

`ring.Ring` allows user to shard by consistent hashing. What if, the underlying connection talks to Redis Sentinel for automatic failover?

*My proposal:*

In this line, [ring.go#L154](https://github.com/go-redis/redis/blob/v4/ring.go#L154), addClient can choose to use  [NewFailoverClient](https://github.com/go-redis/redis/blob/v4/sentinel.go#L65) if failover settings is provided to `ring.Ring`. `NewFailoverClient` already returns instance of `*Client` so the code change could be very minimal.

What do you guys think? This setup allows Redis to be used as horizontally expanding caching store just like Redis Cluster, but significantly lower operational headache.

**Comment by vmihailenco** [comment]
Well, high availability / failover is achieved by removing dead shards. All that without any guarantees (consistency or data safety) but also with 0 maintenance.

As for the using redis.Ring and Sentinel - that would be completely different client, because now Ring pings all shards itself. Overall I am skeptical because this is what Redis Cluster is supposed to solve. But if you want to contribute such client - I will be happy to review the code :)

**Comment by didip** [comment]
Thank you for entertaining the idea, I am currently playing with it right now. Will send PR when it's acceptable.

It's true that Ring performs health checks so an existing key would move to a different shard. This works great for set/get key-value.

But for list or set data structures, a brief downtime could yield a surprising result. Example:

1. `a = [1,2,3]` is a list with 3 values, stored in `shard0`

2. `shard0` is down for 10 minutes. New values for `a` are now going to `shard1`. Example: `a = [4,5,6]`

3. `shard0` came back. It now contains only `a = [1,2,3]`, which is incorrect.

Regarding Redis Cluster, my team spent about 3 weeks trying to setup production environment, complete with orchestration tools. Unfortunately, the tooling for it is far from maturity, I think. Not at the level of `nodetool` for Cassandra. This is why we are switching to Ring.

**Comment by vmihailenco** [comment]
Yeah, Ring provides zero guarantees and I use it only for caching and/or aggregating data that I can restore later. I tried to make it clear in docs :)

As for the building cluster on Redis Server + Redis Sentinel - my biggest concern is the tooling too :) I honestly don't see how it can be simpler than Redis Cluster, because Redis Cluster is integrated version of Redis Server and Redis Sentinel with some tools :)

**Comment by didip** [comment]
I will close this ticket and open a new one when I have a PoC.

**Comment by vmihailenco** [comment]
Cool, but please rebase your work on v5 branch.

**Comment by rafaeleyng** [comment]
Hey @didip, just a question. Did you end up using a ring without Sentinel on the shards?

I'm currently facing the same issue and I'm pretty sure that avoiding Sentinel on the shards is the way to go (besides, the only way supported by the lib 😄).
