### ISSUE TITLE
cmd.setReadTimeout(readTimeout(timeout)) can cause blocking commands to wrongfully time out

### ISSUE THREAD

**Issue by SergeyTsalkov** [go-redis/redis#647]
When a blocking command like BRPOPLPUSH is used, this library uses `cmd.setReadTimeout(readTimeout(timeout))` to set a command timeout for 1 second more than the time we ask to block for. However, the only true guarantee in redis's blocking commands is that they won't return sooner than the time requested. They can take longer, and on my highly loaded redis server I've seen returns as much as 1.5 seconds late. This means the BRPOPLPUSH returns an error like `read tcp 127.0.0.1:48464->127.0.0.1:6379: i/o timeout`. If you're checking the response to BRPOPLPUSH and acting on it, and you have MaxRetries enabled, it's possible to miss the fact that an item was moved between lists.

Rather than hardcoding an extra second in readTimeout(), could you make that duration configurable in redis.Options? I'd also recommend a default of at least 5 seconds because it's better to wait longer than risk dropping an answer by mistake. Personally, I'd make it double the BRPOPLPUSH block time.

**Comment by vmihailenco** [comment]
Thanks for detailed explanation. Please take a look at https://github.com/go-redis/redis/compare/fix/cmd-timeout?expand=1:
- timeout for blocking commands is increased. I don't want to introduce an option for this, because very few people are able to properly tune it. Currently it is `timeout + 5*time.Second`, but we can make it `time + 10*time.Second` if you think that will be better
- blocking commands are no longer retried even if `MaxRetries > 0`

**Comment by SergeyTsalkov** [comment]
Thank you for the quick fix! It looks good, but I think 10 seconds is better! There's really no downside to increasing it since tcp timeouts (especially to a localhost redis server) are super-rare, and not dropping replies on the floor is super-important.

**Comment by vmihailenco** [comment]
Okay, increased to 10 seconds.

**Comment by vmihailenco** [comment]
Fixed by https://github.com/go-redis/redis/pull/648
