### ISSUE TITLE
Random MOVED errors under concurrent load when ClusterClient configured with port-only addrs

### ISSUE THREAD

**Issue by sqaxomonophonen** [go-redis/redis#771]
Please refer to my test program here: https://github.com/go-redis/redis/issues/753#issuecomment-389121219

In trying to figure out why your "cluster races" test cases succeed while my program fails, I discovered that your cluster client is configured with full addresses like `"127.0.0.1:8220"`, while my program uses a port-only address (`":7000"`), and indeed, my program stops failing when I instead connect to `"127.0.0.1:7000"`. I'm also seeing the exact same behavior on the Redis Cluster booted by your test cases (by inserting a `select{} // block forever` somewhere so I could run my program against it).

I'm seeing the same problem when using addresses like `"0.0.0.0:8220"` and `"localhost:8220"`. Only `"127.0.0.1:8220"` works (or actually, the entire `127.0.0.0/8` block seems to work)

I'd like send a test case patch to replicate the problem, but it's non-trivial because there's an internal consistency check (`clusterClient.GetState().IsConsistent()` in `cluster_test.go`) which fails for these problematic addresses, so it seems like the tests know that these addresses are bad, while there's no indication I'm doing anything wrong (except for cryptic random MOVED errors) when using `go-redis` as a package.

Also, I haven't figured out _why_ the errors occur. But it seems like a `go-redis` bug (because it only happens under concurrent load), or: if I'm doing something wrong with my addresses, at least `go-redis` should give me a better error message?

Anyway, I know how to work around the problem now, but I can spare some time to write up a fix if you give some pointers on how to approach it.

**Comment by vmihailenco** [comment]
I think this was reported before and the problem is with Redis Cluster configuration. Specifically:
- Redis cluster reports something like "127.0.0.1:7000"
- But user can only connect to ":7000"

AFAIR this is somehow related to Docker, e.g. "127.0.0.1:7000" is local to Docker container and ":7000" is available to the world. I can be wrong, because I did not try to replicate this myself. See https://github.com/go-redis/redis/issues/701#issuecomment-361909813 for more info.

Are you using Docker? Can you check what addresses are returned by https://redis.io/commands/cluster-nodes and if you can connect to those address using redis-cli?

**Comment by vmihailenco** [comment]
Thanks for the reproduces - I think I've fixed this in master branch.
