### ISSUE TITLE
Why connection not close when the response is "READONLY error"

### ISSUE THREAD

**Issue by todywu** [go-redis/redis#790]
Issue
Firstly I have connected to master redis server and every write operation is OK, but after about one hour, the master and slave redis role interchanged. The write operation on connection with previous master will return  "READONLY error" but the connection is not closed and the error is continue. Can we close the connection after receive an error from redis server?

**Comment by vmihailenco** [comment]
Do you use Redis Cluster or Redis Sentinel?

**Comment by todywu** [comment]
I am not use Redis Cluster and Redis Sentinel. There are two redis server in my runtime environment, one is master and another is slave. The redis client use NewClient() to get a client instance and Addr is redis domain name. When redis server role is interchanged, the redis domain name will be mapped to new master server.  New connection will connect to this new master server and wirte operation is  OK, but the old connection is response "READONLY error" contineouly.

**Comment by vmihailenco** [comment]
So to answer your question - "READONLY error" connections are not closed, because `Client`, `ClusterClient`, `FailoverClient`, and `Ring` does not require it and such connection is perfectly healthy - it is just read-only.

That said your use case makes sense and closing connections on read-only errors is probably fine and should not affect existing code.

**Comment by todywu** [comment]
I am certainly seeing your commit and thank you very much for reslove this issue.
