### ISSUE TITLE
Decide what to do when PubSub channel is full

### ISSUE THREAD

**Issue by vmihailenco** [go-redis/redis#887]

**Comment by tillberg** [comment]
For what it's worth, I also ran into the same error message in #879, "... discarding bad PubSub connection ...". The error was of course in my own code, and I eventually convinced myself of that by adding logging at https://github.com/go-redis/redis/blob/0064936c5b77c874f8e1f089c955ec8bef3818c4/pubsub.go#L430 if the channel write blocked for more than five seconds, e.g.: 

``` golang
case *Message:
loop:
	for {
		select {
		case c.ch <- msg:
			break loop
		case <-time.After(5 * time.Second):
			internal.Logf("pubsub blocked writing to subscription channel for >5 seconds")
		}
	}
```
There's some expense with doing this (even with a time.Timer instead of time.After) but it could possibly be just enough to help many folks discover that they need to unblock their subscription consumers.
